# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.0.1
_src_path: gh:epics-containers/ioc-template
description: A Generic IOC for the terminal server
git_platform: github.com
github_org: maxherbs
name: ioc-terminalserver
repo_uri: git@github.com:maxherbs/ioc-terminalserver.git
rtems: false
